### ISSUE TITLE
PR URL 검증

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-baton#238]
### 버그 사항
리뷰요청 생성할 때 URL `이상한 URL`로 입력해도 그냥 생성이되네요.
이것도 검증하면 좋을것 같긴해요.
이상한 URL로 글 생성하고 나서 해당 글의 코드보러가기 버튼 누르면
`https://baton-review.com/runner-post/이상한%20URL`로 이런 URL로 이동하게 되네요
 

### 버그 simulation
1. 글생성
2. PR URL에 아무 URL이나 작성
3. 해당 글 보기
4. 코드보러가기 버튼 클릭
 

### 원하던 상황
URL 입력 시 validate를 하는걸 예상했어요.
존재하지 않는 URL로 접속하면 404가 뜨는게 맞지 않을까 싶네여
 

### **Screenshots**
<img width="1216" alt="image" src="https://github.com/woowacourse-teams/2023-baton/assets/96301958/781e2c5f-0cdb-48df-8e4a-321eaf99a8d1">

**Comment by cookienc** [comment]
감사합니다
