### ISSUE TITLE
로그아웃해도 삭제 버튼이 남아있어요

### ISSUE THREAD

**Issue by nuyh99** [woowacourse-teams/2023-baton#240]
### 버그 사항
- 제가 쓴 글을 보다가 로그아웃을 해도 삭제 버튼이 존재합니다
 

### 버그 simulation
- 자기가 쓴 글 들어가기 -> 로그아웃 -> 삭제 버튼 존재
 

### 원하던 상황
- 새로고침? 등으로 로그아웃 유저의 뷰가 보이기

### **Screenshots**
<img width="1254" alt="image" src="https://github.com/woowacourse-teams/2023-baton/assets/93072571/8fd4faf3-92aa-4d3f-b007-8394925aaab1">

**Comment by eunbii0213** [comment]
버튼을 눌러도 삭제가 되진 않지만 "다시 로그인 해주세요"같은 alert가 필요할 것 같아요.
