### ISSUE TITLE
목록 화면에서 사용자 프로필 이미지 정렬이 맞지 않습니다

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-baton#242]
### 버그 사항
![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/3e23a2fd-058d-4eb9-ad76-fa830509cf25)

사용자 프로필 이미지 정렬이 이상해요.

![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/bcde3b23-9479-4b9d-b2a1-e9bb42fc6af7)

![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/cf23c227-a540-4479-b5b7-09be4000c3f8)

### 버그 simulation

목록 화면에 접속합니다.

### 원하던 상황

정렬이 깔끔하게 되어있어야 합니다

**Comment by gyeongza** [comment]
justify-content: center로 되어있어 이름이 길어지면 삐져나오네요 ㅎㅎ 감사합니다~!
