### ISSUE TITLE
조회수가 올바르게 올라가지 않습니다

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-baton#243]
### 버그 사항
조회수를 동시에 100회 올릴 때 100회 올라가지 않습니다.

### 버그 simulation
![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/b91e4ce5-f36e-4c4e-a965-fe9f81889450)

|전|후|
|:-:|:-:|
|![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/3f889e99-6c8c-4a38-acaa-c7891a9d6ab7)|![image](https://github.com/woowacourse-teams/2023-baton/assets/20203944/b0208174-8803-4da7-9cab-633a73cd81e0)|

조회수를 올리는 것으로 여겨지는 API를 동시에 100회 호출하였을 때 약 30회만 올라갑니다.

### 원하던 상황
조회수가 정확하게 100회 올라가야 합니다.

**Comment by shackstack** [comment]
같은계정으로 같은글을 여러번 클릭하면 조회수가 오르는데 그게 정상정인지는 의문이네요
